import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fun Safri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href={Image} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
